create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table public.roles (
  id bigint generated by default as identity primary key,
  name text unique not null,
  description text,
  created_at timestamptz default now()
);

create table public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role_id bigint not null references public.roles(id) on delete cascade,
  created_at timestamptz default now(),

  unique (user_id, role_id)
);